### ISSUE TITLE
Bloc Авторизации пользователя

### ISSUE THREAD

**Issue by artem-zaitsev** [boostgrade/wtgt_delta#10]
## Описание задачи

В приложении ViewModel не может взаимодействовать с repository и другими сущностями напрямую.

Фасадом этого взаимодействия является Bloc.
В данной задаче необходимо реализовать Bloc для моудля авторизаци, события, состояния данных.

Блок должен лежать в папке /lib/src/features/auth/services/

## Требования

* [ ] **! Перед реализацией задачи показать проектирование ментору !**
* [ ] Блок лежит в папке /lib/src/features/auth/services/
* [ ] События лежат в папке /lib/src/features/auth/services/events
* [ ] Состояния в /lib/src/features/auth/services/states

## Артефакты

- bloc: https://pub.dev/packages/bloc

**Comment by NetLost** [comment]
1) События:

**Comment by NetLost** [comment]
1) События
- Логирование по номеру телефона
- Логирование по facebook
- Логирование по apple
- Логирование по google
- Логирование по Vk
- Разлогиниться
- Регистрация
2) Состояния
- Loading
- Loaded
- Error
- Base/wait/empty?
3) При логировании мы достаем токен из hive и кидаем его в апи. Получаем responce. Сохраняем токен...(будет новая модель?)
4) При регистрации кидаем request модель
5) При разлогине кидаем запрос и удаляем токен.
